// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace MicrosoftIdentity.Data
{
    public partial class Student
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string Country { get; set; }
        public int? DepartmentId { get; set; }

        public virtual Department Department { get; set; }
    }
}